### ISSUE TITLE
Area code is not set

### ISSUE THREAD

**Issue by grafikchaos** [renatocason/magento2-module-mq#1]
Running a consumer via the command line produces the following error:

```
Error processing message: Area code is not set
```

Looks like it's coming from the `\Magento\Framework\App\State`. I've seen this issue pop up in other third-party modules that introduce custom CLI commands. I'll open up a PR shortly

**Comment by renatocason** [comment]
Hi @grafikchaos,

Thanks for the contribution, I merged the PR (just removed a repo reference in _composer.json_).
From the commits, I saw you were using it in version 2.2. Did everything go smoothly?
I'm planning to do the update soon, as well.

Regards,
Renato

**Comment by grafikchaos** [comment]
I haven't had a chance to test it in 2.2.1 sandbox environment yet, but once the version dependencies were updated it at least installed smoothly.
