### ISSUE TITLE
Compare with Magento 2.3 message queue

### ISSUE THREAD

**Issue by onlinebizsoft** [renatocason/magento2-module-mq#12]
Since Magento 2.3 release, they have migrated message queue to Community version and their built-in message queue implementation support RabbitMQ as well. So do you have any comparison for cons and pros for using this module instead of built-in one?

**Comment by renatocason** [comment]
Hi @onlinebizsoft ,

From my point of view, there are only a few cases where using this module can have its advantages after the 2.3 release which, as you mention, includes the message queue part in the community edition.
* You are implementing a module that needs to be used also on 2.2 and/or 2.1
* You are upgrading an integration that uses this module from 2.1 or 2.2 and you don't want to completely rewrite it
* You are implementing a custom broker and want to save time (the APIs in this module are easier) 

Hope that helps!

Regards,
Renato

**Comment by onlinebizsoft** [comment]
@renatocason I got it. Thanks for your information
