### ISSUE TITLE
Thoughts on using Magento's built-in cron?

### ISSUE THREAD

**Issue by mlambley** [renatocason/magento2-module-mq#15]
Good day,

I was wondering what your thoughts are on using Magento's built-in cron, rather than running commands from the command line.

The reason why I'm considering this is because we don't have control over our customers' systems and therefore cannot ensure that queues are running, whereas Magento's built-in cron automatically runs every minute so we could use that instead.

I'm looking at [mq-mysql](https://github.com/renatocason/magento2-module-mq-mysql) and I'm thinking that if I created a cron task which, once per minute, detects whether a previous queue process is running (somehow) and basically does what `StartConsumerCommand` does in fetching the broker, consumer, etc.

What are your thoughts on this? Can you foresee negative side-effects I haven't considered?

Thank you.

**Comment by mlambley** [comment]
I'm going to try to use [m2-ce-cron](https://github.com/magemojo/m2-ce-cron) to avoid overlapping crons, and then implement a cron job which runs every minute to process `$limit` records. I'll let you know how I go.

**Comment by renatocason** [comment]
Hi @mlambley ,

At the time I started working on the extension m2-ce-cron didn't exist, so using Magento's crons wasn't really an option given all their linked problems. On top of that, the idea in most cases is to have the consumer always up and running to process any message as soon as possible.
If that isn't a concern in your case, I see no issue in implementing a Magento cron that uses the broker and checks/processes new messages directly with the _peek_, _acknowledge_ and _reject_.
The fact that the extension is very simple and minimal allows you to do that very easily, probably one of the few reasons to still use it now that Magento ships its own MQ extension on the Open Source version, too :)

Hope that helps, and keep me posted - I'm definitely interested on knowing how that goes!

Regards,
Renato

**Comment by mlambley** [comment]
The Magento MQ extensions seem good, but I don't have control over customer servers and so I don't want the extra hassle of having them install and monitor an AMQP system. I wanted one which just works off the database which is how I come across your project in the first place.

The default Magento cron is no good for this, because it spawns a new process every minute, but ce-cron works great. I've got it implemented on one of our customers' systems, with queues set to try every 5 minutes 60 times, and it works well. Jobs don't necessarily start right away, rather they might start anywhere up to a minute after their scheduled start time, but that's acceptable in my case.

I am a little hesitant to say to every customer "BTW you're using this completely revised cron now" but I'll take the chance.

Sometime in the future I'm going to look into firing events when jobs succeed / retry / completely fail.

Cheers.
