### ISSUE TITLE
Declare compatibility with PHP 7.2 in releases for Magento 2.2.x

### ISSUE THREAD

**Issue by AlexandreKhayrullin** [renatocason/magento2-module-mq#21]
Hello.

For a project we are developing, we chose your module to ensure Message Queue support on Magento 2.2.11, to replace Magento's native one which isn't available in the Open Source edition.

The issue we're having is that installing the module via composer on our environments with Magento 2.2.11 is currently impossible:
- Picking a 1.1.x release (1.2.x in the case of the MySQL adapter) results in a conflict with the Magento Framework's version (which is normal, since it's for Magento 2.3 without declared backwards compatibility)
- Picking a 1.0.x release (1.1.x in the case of the MySQL adapter) results in a conflict with the PHP version, since the module is declared as compatible with PHP 7.0 and 7.1 only.

As of 2.2.11, Magento supports PHP 7.2, as seen here: https://github.com/magento/magento2/blob/2.2.11/composer.json . By downloading the base module and both MySQL and AMQP adapters, and placing them in app/code instead, it works, I could successfully send and receive messages via both methods without any issues.

Is it possible to please declare a compatibility with PHP 7.2 in Magento 2.2.x releases in the base module and both MySQL and AMQP adapters?

**Comment by renatocason** [comment]
Hi @AlexandreKhayrullin ,

I prepared a release for each package to fix this, you should be able to do this now.
Can you let me know if you find any issue?

Thanks,
Renato

**Comment by AlexandreKhayrullin** [comment]
Hi Renato.

I managed to install the packages on a 2.2 version and tested both adapters, so far they seem to work as intended. Thank you!
I'll be sure to let you know if I find any issues.

Best regards,
Alex

**Comment by renatocason** [comment]
Hi @AlexandreKhayrullin ,

Amazing, thanks! I will close this for now but feel free to re-open in case you find any issue.

Regards,
Renato
