### ISSUE TITLE
Magento 2.2.x support?

### ISSUE THREAD

**Issue by peterjaap** [renatocason/magento2-module-mq#4]
Is there Magento 2.2.x support coming?

**Comment by peterjaap** [comment]
Just tested it, seems to work fine under 2.2.x. Could you loosen the composer restrictions?

**Comment by renatocason** [comment]
Hi @peterjaap,

Yep, the modules are not using many framework functions so I expect them to work fine. I will make some test today and fix the composer requirements.

Regards,
Renato

**Comment by peterjaap** [comment]
Great! Don't forget https://github.com/renatocason/magento2-module-mq-mysql and https://github.com/renatocason/magento2-module-mq-amqp :)

**Comment by renatocason** [comment]
Hi @peterjaap ,

Done, I also tested that Packagist has the updated version.
Will try to add some more unit tests to the modules, but in the meantime just let me know if you find any issue.

Thanks,
Renato

**Comment by peterjaap** [comment]
Thanks!
