### ISSUE TITLE
xml message Schema

### ISSUE THREAD

**Issue by bouzakherOR** [renatocason/magento2-module-mq#5]
Hello,

What value we can put in place of "int" in the ce_mq.xml file :
**messageSchema="int"**, can we put **json** or **text/plain** ? i tried to chage but not working.

thank you.

**Comment by renatocason** [comment]
Hi @bouzakherOR ,

You can use anything that can be serialized.
If you are using service contracts as per Magento 2 best practice, you can use the interface that your model implements. Let me know if that's clear, otherwise I can provide an example.

Regards,
Renato
