### ISSUE TITLE
Consumer does not run after deployment

### ISSUE THREAD

**Issue by peterjaap** [renatocason/magento2-module-mq#7]
Hi @renatocason,

We're facing an issue with the consumer. We start it like this;

```
nohup php bin/magento ce_mq:consumers:start lcp.product.prewarm &> /data/web/current/var/log/consumer_prewarm.log &
```

But when we do a deployment, the `current` symlink (which the public folder points to) will point to the new deployment. At that point, the process does keep running, but it doesn't work anymore.

Do you have an idea how to circumvent this? Right now, we kill the process every 5 minutes and restart it through a cron, which kinda defeats the purpose of a consumer.

**Comment by renatocason** [comment]
Hi @peterjaap ,

Unfortunately, that is a problem in general when running a command as a process along with an application behind php-fpm or apache mod_php.
In most of the cases (and I think Magento Commerce Cloud works like that) the consumer process is killed and restarted as part of the deployment process.
The solution I prefer is implemented using containers, as the consumer is a process running on its own and updated separately, so there is no mix between using the same code base as a process and behind php-fpm or apache mod_php.

Hope that makes sense!

Renato

**Comment by peterjaap** [comment]
@renatocason thanks! We'll implement killing/starting as a part of the deployment process :)
